services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-zvonok
    environment:
      POSTGRES_USER: zvonok_admin
      POSTGRES_PASSWORD: zvonok_password
      POSTGRES_DB: zvonok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zvonok_admin"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
